#!/usr/bin/env bash

set -ex

npm list mdpdf -g || npm install mdpdf -g

INPUT="RESUME"
OUTPUT="export/Resume-AlekseyKuznetsov.pdf"
# mdpdf has a bug with line brankes, see:
# https://github.com/BlueHatbRit/mdpdf/issues/46
mdpdf "$INPUT.md" --format=A4 && mv "$INPUT.pdf" "$OUTPUT" && open "$OUTPUT"

