#!/usr/bin/env bash

set -ex

npm list md-to-pdf -g || npm install md-to-pdf -g

INPUT="RESUME"
OUTPUT="export/Resume-AlekseyKuznetsov.pdf"

md-to-pdf "$INPUT.md" && mv "$INPUT.pdf" "$OUTPUT" && open "$OUTPUT"

